import {
  DiscoverItem,
  WalletTransaction,
  PriorityUrgentItem,
  PriorityMeetingItem,
  PriorityPaymentItem,
  PriorityAIBrief,
} from '../types';

export const INITIAL_DISCOVER_ITEMS: DiscoverItem[] = [
  {
    id: 'disc_1',
    title: 'AfroArtisan Atelier & Design Hub',
    subtitle: 'Handcrafted luxury apparel, authentic beadwork & Pan-African home decor',
    category: 'businesses',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80',
    badge: 'Verified Business',
    rating: 4.9,
    reviewCount: 328,
    location: 'Nairobi & Worldwide Shipping',
    distanceKm: 2.4,
    verified: true,
    tags: ['Fashion', 'Artisans', 'Export', 'Mobile Money'],
    actionLabel: 'Explore Catalog',
    authorName: 'AfroArtisan Collective',
    authorHandle: '@afroartisan:wat.chat',
    authorAvatar: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=150&auto=format&fit=crop&q=80',
    description: 'Premier artisan house empowering over 250 women cooperatives across Kenya, Ghana, and Rwanda.',
  },
  {
    id: 'disc_2',
    title: 'Savannah Tech & Matrix Developers Forum',
    subtitle: 'Join 14,800+ builders engineering decentralized Matrix 2.0 & WebRTC applications',
    category: 'communities',
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80',
    badge: 'Trending Community',
    membersCount: 14820,
    location: 'Pan-African / Global',
    verified: true,
    tags: ['Matrix', 'Rust', 'WebRTC', 'Open Source'],
    actionLabel: 'Join Space',
    authorName: 'Savannah Dev Network',
    authorHandle: '@savannahdev:wat.chat',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    description: 'Weekly tech huddles, code reviews, crypto protocol discussions and hackathon sponsorships.',
  },
  {
    id: 'disc_3',
    title: 'Ethiopian Single-Origin Yirgacheffe Beans (500g)',
    subtitle: 'Direct-trade sun-dried organic specialty coffee with jasmine & citrus notes',
    category: 'products',
    image: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=600&auto=format&fit=crop&q=80',
    priceTag: 'R380.00',
    rating: 4.95,
    reviewCount: 142,
    location: 'Addis Ababa & Direct Courier',
    tags: ['Coffee', 'Organic', 'Gourmet', 'Direct Trade'],
    actionLabel: 'Order via WAT Pay',
    authorName: 'Yirga Highlands Farm',
    authorHandle: '@yirgacoffee:wat.chat',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'disc_4',
    title: 'Pan-African Fintech & Decentralized Commerce Summit 2026',
    subtitle: 'Keynote sessions on cross-border instant settlements, Matrix federation, and AI agents',
    category: 'events',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&auto=format&fit=crop&q=80',
    badge: 'Live Keynote',
    eventDate: 'Sept 14-16, 2026 • Cape Town & Virtual',
    location: 'Cape Town ICC / Live on WAT',
    tags: ['Fintech', 'Payments', 'Summit', 'AI'],
    actionLabel: 'Reserve VIP Pass',
    authorName: 'WAT Summit Team',
    authorHandle: '@summit:wat.chat',
    authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'disc_5',
    title: 'Lumina Creative Strategy & Growth Agency',
    subtitle: 'Brand identity, performance growth marketing & enterprise communications',
    category: 'services',
    image: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=600&auto=format&fit=crop&q=80',
    badge: 'Top Rated Pro',
    rating: 4.88,
    reviewCount: 96,
    location: 'Johannesburg / Remote',
    distanceKm: 8.1,
    verified: true,
    tags: ['Consulting', 'Design', 'Marketing', 'Enterprise'],
    actionLabel: 'Book Consultation',
    authorName: 'Lumina Agency',
    authorHandle: '@lumina:wat.chat',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'disc_6',
    title: 'Global Macro & African Markets Intelligence Channel',
    subtitle: 'Daily morning briefs on FX rates, sovereign bond yields, commodity prices & VC funding',
    category: 'channels',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&auto=format&fit=crop&q=80',
    badge: '48k Subscribers',
    membersCount: 48900,
    tags: ['Economy', 'Finance', 'Crypto', 'Insights'],
    actionLabel: 'Subscribe Free',
    authorName: 'African Macro Insights',
    authorHandle: '@africamacro:wat.chat',
    authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'disc_7',
    title: 'The Greenhouse Rooftop & Artisan Bakery',
    subtitle: 'Sourdough bakery, specialty espresso bar & collaborative co-working lounge',
    category: 'nearby',
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&auto=format&fit=crop&q=80',
    badge: 'Open Now • 1.2 km',
    rating: 4.92,
    reviewCount: 512,
    location: 'Rosebank, Johannesburg',
    distanceKm: 1.2,
    tags: ['Cafe', 'Work Friendly', 'Bakery', 'Free WiFi'],
    actionLabel: 'View Menu & Order',
    authorName: 'The Greenhouse',
    authorHandle: '@greenhouse:wat.chat',
    authorAvatar: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_WALLET_TRANSACTIONS: WalletTransaction[] = [
  {
    id: 'tx_101',
    type: 'incoming',
    amount: 2500,
    currency: 'ZAR',
    counterpartyName: 'John Smith',
    counterpartyHandle: '@johnsmith:wat.chat',
    counterpartyAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    category: 'Transfer',
    timestamp: Date.now() - 1000 * 60 * 42,
    status: 'completed',
    note: 'Consulting retainer payment for Q3 strategy',
    referenceId: 'WAT-TX-984210',
  },
  {
    id: 'tx_102',
    type: 'outgoing',
    amount: 850,
    currency: 'ZAR',
    counterpartyName: 'ABC Services & Cloud Hosting',
    counterpartyHandle: '@abcservices:wat.chat',
    counterpartyAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    category: 'Services',
    timestamp: Date.now() - 1000 * 60 * 60 * 3.5,
    status: 'completed',
    note: 'Dedicated Matrix homeserver & TURN relay cluster monthly tier',
    referenceId: 'WAT-TX-984188',
  },
  {
    id: 'tx_103',
    type: 'incoming',
    amount: 5000,
    currency: 'ZAR',
    counterpartyName: 'Apex Capital Partners',
    counterpartyHandle: '@apexcapital:wat.chat',
    counterpartyAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    category: 'Business',
    timestamp: Date.now() - 1000 * 60 * 60 * 22,
    status: 'completed',
    note: 'Advisory milestone tranche 2',
    referenceId: 'WAT-TX-983992',
  },
  {
    id: 'tx_104',
    type: 'incoming',
    amount: 1420,
    currency: 'ZAR',
    counterpartyName: 'Sarah Jenkins',
    counterpartyHandle: '@sarah:wat.chat',
    counterpartyAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    category: 'Marketplace',
    timestamp: Date.now() - 1000 * 60 * 60 * 36,
    status: 'completed',
    note: 'Kente jacket order settlement',
    referenceId: 'WAT-TX-983540',
  },
  {
    id: 'tx_105',
    type: 'outgoing',
    amount: 320,
    currency: 'ZAR',
    counterpartyName: 'The Greenhouse Rooftop Cafe',
    counterpartyHandle: '@greenhouse:wat.chat',
    counterpartyAvatar: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=150&auto=format&fit=crop&q=80',
    category: 'Services',
    timestamp: Date.now() - 1000 * 60 * 60 * 48,
    status: 'completed',
    note: 'Meeting lunch & artisan coffee',
    referenceId: 'WAT-TX-983110',
  },
];

export const INITIAL_PRIORITY_URGENT: PriorityUrgentItem[] = [
  {
    id: 'urg_1',
    roomId: 'room_kwame',
    senderName: 'Kwame Mensah',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    previewText: 'Can you approve the Matrix 2.0 sliding-sync pull request before our client demo?',
    timeAgo: '12m ago',
    priorityTag: 'High Priority',
  },
  {
    id: 'urg_2',
    roomId: 'room_business',
    senderName: 'AfroArtisan Collective',
    senderAvatar: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=150&auto=format&fit=crop&q=80',
    previewText: 'Wholesale order #482 confirmed with 35 units ready for dispatch to UK courier.',
    timeAgo: '34m ago',
    priorityTag: 'Client Proposal',
  },
  {
    id: 'urg_3',
    roomId: 'room_amara',
    senderName: 'Amara Okafor',
    senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    previewText: 'Security audit cross-signing verification keys require master password re-auth.',
    timeAgo: '1h ago',
    priorityTag: 'Overdue Action',
  },
];

export const INITIAL_PRIORITY_MEETINGS: PriorityMeetingItem[] = [
  {
    id: 'meet_1',
    title: 'Product Sprint & Matrix 2.0 Sync',
    time: '15:30 (in 45 mins)',
    roomId: 'room_dev_africa',
    type: 'video',
    participants: [
      { name: 'Amara', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80' },
      { name: 'Kwame', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80' },
      { name: 'Brian', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80' },
    ],
  },
  {
    id: 'meet_2',
    title: 'Enterprise Client Architecture Brief',
    time: '17:00 Today',
    roomId: 'room_kwame',
    type: 'video',
    participants: [
      { name: 'Lusimadio', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80' },
      { name: 'Zainab', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80' },
    ],
  },
];

export const INITIAL_PRIORITY_PAYMENTS: PriorityPaymentItem[] = [
  {
    id: 'pay_1',
    amount: 3450,
    currency: 'ZAR',
    counterpartyName: 'Cloud Infrastructure Ltd',
    dueDate: 'Today, 18:00',
    invoiceId: 'INV-2026-8831',
    description: 'High-availability TURN & JVB Video Relay Server cluster renewal',
  },
];

export const INITIAL_AI_BRIEF: PriorityAIBrief = {
  summary: '5 important updates occurred across your chats, business pipeline & wallet while you were away:',
  bulletPoints: [
    'John Smith accepted your Q3 advisory proposal and transferred R2,500 retainer to your WAT Wallet.',
    'AfroArtisan logged 17 pending wholesale orders totaling R127,450 revenue this month.',
    'Kwame Mensah pushed the sliding-sync rust module to room #savannah-dev.',
    'Amara scheduled a 15:30 video call for the security cross-signing audit.',
    'Sarah Jenkins recommended "The Greenhouse Rooftop" in Rosebank for tomorrow\'s investor huddle.',
  ],
  keyActions: [
    'Reply to John Smith with meeting calendar link',
    'Review wholesale dispatch invoice for AfroArtisan',
    'Join 15:30 WebRTC call with Dev Team',
  ],
};
